language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    # Install composer
    - wget http://getcomposer.org/composer.phar
    - php composer.phar update --prefer-stable

script:
    - ./bin/phpmetrics src
    - ./bin/phpcs --standard=vendor/escapestudios/symfony2-coding-standard/Symfony2/ src/ tests/

    # Test on stable versions
    - ./bin/phpunit

    # Test on lowest versions
    - php composer.phar update --prefer-lowest
    - ./bin/phpunit
